### ISSUE TITLE
how to use suber with react

### ISSUE THREAD

**Issue by unship** [oskarhane/suber#5]
If contextTypes is not defined, then context will be an empty object.

how to write a BusProvider

**Comment by oskarhane** [comment]
Hi @biolee,

I haven't gotten around to create a provider for React yet. I've done it for Preact on the `preact` branch of https://github.com/oskarhane/react-suber/tree/preact
Scroll down to see the API and check out the tests as well.

I'm happy to take contributions on porting that to React (on the `master` branch of that repo) if you want to.

Closing this here since it's an issue in the https://github.com/oskarhane/react-suber repo.
